name: "Template for install OpenVPN"

inputs:
  ovpn_config_file:
    description: "OVPN Config File"
    required: true
  ovpn_cert_pass:
    description: "OVPN Cert Pass"
    required: true
  ovpn_pass:
    description: "OVPN Cert Pass"
    required: true
runs:
  using: "composite"
  steps:
      - name: Installl OpenVPN
        shell: bash
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install openvpn -y > /dev/null
      - name: Config VPN
        shell: bash
        run: |
          echo "${{ inputs.ovpn_config_file }}" > cicd.ovpn  
          echo "${{ inputs.ovpn_cert_pass }}" > vpn_pass.txt    
          echo "${{ inputs.ovpn_pass }}" > pass.txt 
      - name: connect on VPN
        shell: bash
        run: | 
         sudo openvpn --config cicd.ovpn --askpass vpn_pass.txt --daemon
      - name: Waiting VPN connect
        shell: bash
        run: | 
         sleep 10
      - name: Checking connection VPN
        shell: bash
        run: |
          found_int_count=$(ip address | grep -o " tun" | wc -l)
          if [ $found_int_count -eq 0 ]; then
            echo "ERRO: Interface VPN not find!"
            exit 1
          fi
