name: Python Network 
on:
  workflow_dispatch:
jobs:
  docker-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - uses: dopplerhq/cli-action@v1 
    - name: set envs agent github actions
      run: |
        doppler secrets download --no-file --format=docker >> $GITHUB_ENV; 
        echo "::set-env name=AWS_ACCESS_KEY::red" 
      env:
         DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_PRD }}
    - name: Mask Vars
      run: echo "::add-mask::$AWS_ACCESS_KEY"
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: List Envs
      run: cat ec2_description.py