name: Python Network
on:
  workflow_dispatch:
jobs:
  docker-build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: List Archives 
      run: ls -la
    - name: Build Image docker
      id: build-image
      run: |
        docker build -t python-network .