name: Sonar Qube Scan
on:
  pull_request:

jobs:
   sonarcloud:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=python-app
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: SonarQube Quality Gate check
      uses: campos-pay/sonarqube-quality-gate-action@master
      id: sonar
      timeout-minutes: 5
#       with:
#         GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: PR Comment
      uses: actions/github-script@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: ${{ github.event.number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `👋 Ola se voce esta vendo esse erro tem algo errado na sua PR verifique o SonarQube para mais detalhes :warning:
            ${{ steps.sonar.outputs.quality_status }}`
          })
          
      #Test Sonar Script
#     - name: Get Sonar Status and comment PR
#       if: success()
#       uses: campos-pay/Sonar-status-check@main
#       with:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         SONAR_URL: ${{ secrets.SONAR_HOST_URL }}
#         SONAR_PROJETCKEY: python-app
#         GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
