name: Sonar Qube Scan
on:
  pull_request:

jobs:
   sonarcloud:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=python-app
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
    - name: SonarQube Quality Gate check
      uses: sonarsource/sonarqube-quality-gate-action@master
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #Test Sonar Script
    - name: Get Sonar Status and comment PR
      if: failure()
      uses: campos-pay/Sonar-status-check@main
      with:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_PROJETCKEY: python-app
        GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
