name: Sonar Qube Scan
on:
  pull_request:

jobs:
   sonarcloud:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting 
        #
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=python-app
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      #Test Sonar Script
    - name: SonarQube Pull Request Comment
      uses: campos-pay/sonarqube-pr-comment@main
      if: always()
      with:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_PROJECTKEY: python-app
        GITHUB-TOKEN: ${{ secrets.GITHUB_TOKEN }}
