name: Test connect OVPN 
on:
  workflow_dispatch:
#   schedule:
#     - cron: '00 00 * * MON'
    
jobs:
  ovpn:
    name: OVPN
    runs-on: ubuntu-20.04
    steps:
      - name: Config VPN
        uses: Guerlielton/Python-Network@main
        with: 
          ovpn_config_file: ${{ secrets.OVPN_CONFIG_FILE }}
          ovpn_cert_pass: ${{ secrets.OVPN_CERT_PASS }}
      - name: kill vpn
        if: always()
        run: sudo killall openvpn

          
