name: Test connect OVPN Mikrotik
on:
  workflow_dispatch:
#   schedule:
#     - cron: '00 00 * * MON'
    
jobs:
  build_docker:
    name: Build Docker
    runs-on: ubuntu-18.04
    steps:
      - name: Config VPN
        uses: Guerlielton/Python-Network@main
        with: 
          ovpn_config_file: ${{ secrets.OVPN_CONFIG_FILE }}
          ovpn_cert_pass: ${{ secrets.OVPN_CERT_PASS }}
          ovpn_pass: ${{ secrets.OVPN_PASS }}
          
