name: Scan Vulnerabilities Trivy
on:
  schedule:
    - cron: '53 5,16 * * *'
    
jobs:
  scan:
    name: Scan Image
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build an image from Dockerfile
        run: |
          date
          docker build -t python-network .
      - name: Scan Vulnerabilities Image Docker.
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'python-network'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
      - name: Discord message
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          message: "Send message test"

